language: node_js
cache:
    yarn: true
    directories:
        - node_modules
node_js:
    - "7.5.0"
before_install:
    - openssl aes-256-cbc -K $encrypted_ed8b93da2aff_key -iv $encrypted_ed8b93da2aff_iv -in id_rsa.enc -out ./id_rsa -d
install:
    - npm install
script:
    - npm run deploy
after_success:
    - npm run gh-pages-travis
env:
    global:
        - DEPLOY_BRANCH="master"
        - SOURCE_DIR="www"
        - TARGET_BRANCH="gh-pages"
        - SSH_KEY="id_rsa"
        - GIT_NAME="travis"
        - GIT_EMAIL="deploy@travis-ci.org"